### PR TITLE
Upgrade peerDeps to react & react-dom 16

### PR DESCRIPTION
**Pull request by AlesJiranek**
since react-dimensions actually works out of the box with react 16 :)

### CODE REVIEW

**Comment by petrogad** [comment]
yes please?

**Comment by gmaclennan** [comment]
Happy to add anyone willing to do this with write and publish access.

**Comment by petrogad** [comment]
@gmaclennan I'll do it.

**Comment by gmaclennan** [comment]
@petrogad fantastic, thanks!

**Comment by jameswomack** [comment]
Will this be merged soon? Need to integrate with a React 16 proggie

**Comment by petrogad** [comment]
updated @jameswomack

**Comment by jameswomack** [comment]
Thanks!

**Pull request merged**
